# Importar controladores con rutas basadas en atributos
controllers:
    resource: ../src/Controller/
    type: attribute

# Definir rutas adicionales directamente
error_404:
    path: /error/404
    controller: App\Controller\ErrorController::show404


    
